apiVersion: l7mp.io/v1
kind: VirtualService
metadata:
  name: ingress-rtp-vsvc-call-id-tag
  ownerReferences:
    - apiVersion: l7mp.io/v1
      kind: VirtualService
      name: ingress-controller-listener
      uid: adfadf
spec:
  updateOwners: True
  selector:
    matchLabels:
      app: l7mp-ingress
  listener:
    spec:
      UDP:
        port: 10000
        options:
          mode: server
    rules:
      - action:
          rewrite:
            - path: /labels/callid
              valueStr: callid 
            - path: /labels/tag
              valueStr: tag
          route:
            destinationRef: /apis/l7mp.io/v1/namespaces/default/targets/ingress-rtp-target