{
 "title": "dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Packet rate on ingress pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_udp_sess_rx_datagrams{envoy_cluster_name=~\".*ingress-.*-rtp.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Packet rate on worker pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_udp_sess_rx_datagrams{envoy_cluster_name=~\".*worker-.*-rtp.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Number of calls",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(envoy_udp_downstream_sess_active{envoy_udp_prefix=~\"ingress.*\"})/4)"
    }
   ]
  },
  {
   "title": "Number of sessions on ingress pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(envoy_udp_downstream_sess_active{envoy_udp_prefix=~\"ingress.*\"}))"
    }
   ]
  },
  {
   "title": "Number of sessions on worker pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(envoy_udp_downstream_sess_active{envoy_udp_prefix=~\"worker.*\"}))"
    }
   ]
  },
  {
   "title": "Mean jitter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "mean_jitter" }
   ]
  },
  {
   "title": "RTT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "round_trip_delay" }
   ]
  },
  {
   "title": "MOS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mos_cq" }
   ]
  },
  {
   "title": "r_factor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "r_factor" }
   ]
  },
  {
   "title": "packet count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "packet_count" }
   ]
  },
  {
   "title": "Health Check",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_cluster_health_check_healthy{envoy_cluster_name=~\"ingress-c-rtp-a-1-.*\"}"
    }
   ]
  }
 ]
}